apiVersion: v1
kind: Secret
metadata:
  name: hm-db-secret
  namespace: homemanagement
type: Opaque
stringData:
  connection-string: "Server=hm-sqlserver;Database=HomeManagement;User Id=sa;Password=CHANGE_ME;TrustServerCertificate=True;"
---
apiVersion: v1
kind: Secret
metadata:
  name: hm-auth-secret
  namespace: homemanagement
type: Opaque
stringData:
  jwt-signing-key: "CHANGE_ME_TO_A_RANDOM_256_BIT_KEY_BASE64"
